# Generated by Django 5.2.4 on 2025-08-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code_primany', models.CharField(max_length=20, unique=True)),
                ('code_alt', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('release_month', models.DateField(blank=True, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actors', models.ManyToManyField(to='videos.actor')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.publisher')),
            ],
        ),
    ]
